league_table/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from league_table.views import TournamentListView
from league_table.views import TournamentDeleteView
from league_table.views import TournamentCreateView
from league_table.views import TournamentInfoView

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TournamentListView.as_view(), name = u"tournament_list_url"),
    url(r'^tournament/delete/(?P<pk>\w+)/$', TournamentDeleteView.as_view(), name = u"tournament_delete_url"),
    url(r'^tournament/create/$', TournamentCreateView.as_view(), name = u"tournament_create_url"),
    url(r'^tournament/info/(?P<pk>\w+)/$', TournamentInfoView.as_view(), name = u"tournament_info_url"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)

league_table/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models


class Participant(models.Model):
    class Meta:
        verbose_name = u"Участник"
        verbose_name_plural = u"Участники"

    name = models.CharField(
        verbose_name = u"имя",
        max_length = 200,
        unique = True
    )

    def __unicode__(self):
        return self.name


class Tournament(models.Model):
    class Meta:
        verbose_name = u"Турнир"
        verbose_name_plural = u"Турниры"

    ROUND_ROBIN_TOURNAMENT = 1
    PLAYOFF_TOURNAMENT = 2
    ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT = 3

    POINTS_FOR_WIN = 3
    POINTS_FOR_DRAW = 1

    TOURNAMENT_TYPES = (
        (ROUND_ROBIN_TOURNAMENT, u"круговая система"),
        (PLAYOFF_TOURNAMENT, u"олимпийская система"),
        (ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT, u"круговая и олимпийская системы"),
    )

    name = models.CharField(
        verbose_name = u"название",
        max_length = 200,
        unique = True,
    )
    type = models.PositiveSmallIntegerField(
        verbose_name = u"тип",
        choices = TOURNAMENT_TYPES,
        blank = False,
        default = ROUND_ROBIN_TOURNAMENT
    )

    def __unicode__(self):
        return self.name


class Group(models.Model):
    class Meta:
        verbose_name = u"Группа"
        verbose_name_plural = u"Группы"

    ROUND_ROBIN_GROUP_SEASON = 1
    ROUND_ROBIN_MAIN_SEASON = 2
    PLAYOFF_REGULAR_SEASON = 3
    PLAYOFF_MAIN_SEASON = 4

    GROUP_TYPES = (
        (ROUND_ROBIN_GROUP_SEASON, u"групповой сезон кругового турнира"),
        (ROUND_ROBIN_MAIN_SEASON, u"основной сезон кругового турнира"),
        (PLAYOFF_REGULAR_SEASON, u"регулярный сезон олимпийской системы"),
        (PLAYOFF_MAIN_SEASON, u"основной сезон олимпийской системы"),
    )

    name = models.CharField(
        verbose_name = u"название",
        max_length = 200,
    )
    type = models.PositiveSmallIntegerField(
        verbose_name = u"тип",
        choices = GROUP_TYPES,
        blank = False,
    )
    level = models.PositiveSmallIntegerField(verbose_name = u"уровень")
    tournament = models.ForeignKey(
        Tournament,
        verbose_name = u"чемпионат",
        on_delete = models.CASCADE
    )
    participants = models.ManyToManyField(
        Participant,
        verbose_name = u"участники"
    )

    def __unicode__(self):
        return u"{}: группа {}".format(self.tournament.name, self.name)


class Match(models.Model):
    class Meta:
        verbose_name = u"Матч"
        verbose_name_plural = u"Матчи"

    group = models.ForeignKey(Group, verbose_name = u"группа")

    participant1 = models.ForeignKey(
        Participant,
        verbose_name = u"первый участник",
        related_name = u"match_participant1",
        null = True, blank = True
    )
    participant2 = models.ForeignKey(
        Participant,
        verbose_name = u"второй участник",
        related_name = u"match_participant2",
        null = True, blank = True
    )
    date = models.DateField(verbose_name = u"дата", null = True, blank = True)
    level = models.PositiveSmallIntegerField(
        verbose_name = u"уровень",
        null = True, blank = True, default = 0
    )
    number = models.PositiveSmallIntegerField(
        verbose_name = u"порядковый номер в уровне",
        null = True, blank = True, default = 0
    )
    participant1_score = models.PositiveSmallIntegerField(
        verbose_name = u"очки первого участника",
        null = True, blank = True
    )
    participant2_score = models.PositiveSmallIntegerField(
        verbose_name = u"очки второго участника",
        null = True, blank = True
    )
    winner = models.ForeignKey(
        Participant,
        verbose_name = u"победитель",
        related_name = u"match_winner",
        null = True, blank = True
    )

    def __unicode__(self):
        date = str(self.date) if self.date else u'дата не назначена'
        name1 = self.participant1.name if self.participant1 else u"неизвестно"
        name2 = self.participant2.name if self.participant2 else u"неизвестно"

        return u"{}: {} - {} ({})".format(
            self.group.tournament.name,
            name1,
            name2,
            date,
        )

league_table/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm

from league_table.models import Tournament, Participant, Group, Match
from league_table.league_table_generator import get_round_robin_group_table
from league_table.league_table_generator import get_playoff_tournament_table
from league_table.league_table_generator import get_playoff_and_round_robin_table

class TournamentCreateForm(ModelForm):
    class Meta:
        model = Tournament
        fields = ["name", "type"]
        widgets = {
            "type": forms.RadioSelect()
        }

    number_of_groups = forms.IntegerField(min_value = 1, initial = 1)
    participants = forms.ModelMultipleChoiceField(
        queryset = Participant.objects.all(),
        to_field_name = "pk",
    )

    def create_group(
        self, name_group, group, tournament, participants
    ):
        new_group = Group.objects.create(
            name = name_group,
            level = group["level"],
            tournament = tournament,
            type = group["type"]
        )
        for participant in participants:
            if participant:
                new_group.participants.add(participant)

        i = 1
        matches = group["matches"]
        for season in matches:
            matches_in_season = matches[season]
            for match in matches_in_season:
                new_match = Match.objects.create(
                    group = new_group,
                    participant1 = match[0],
                    participant2 = match[1],
                    level = season,
                    number = i,
                )
                i += 1


    def save(self, commit = True):
        left_from_group = 2
        instance = super(TournamentCreateForm, self).save(commit = False)
        instance.save()
        tournament_type = self.cleaned_data["type"]
        number_of_groups = self.cleaned_data["number_of_groups"]
        participants = list(self.cleaned_data["participants"])
        print("participants: {}".format(participants))
        if tournament_type == Tournament.ROUND_ROBIN_TOURNAMENT:
            table = get_round_robin_group_table(
                participants, number_of_groups, left_from_group
            )
        elif tournament_type == Tournament.PLAYOFF_TOURNAMENT:
            table = get_playoff_tournament_table(participants)
        elif tournament_type == Tournament.ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT:
            table = get_playoff_and_round_robin_table(
                participants, number_of_groups, left_from_group
            )
        else:
            return None

        for group in table:
            self.create_group(group, table[group], instance, participants)

        return instance

league_table/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import math
from operator import itemgetter

from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView
from django.views.generic import TemplateView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.db.models import Q, F
from django.db.models import Count, Sum

from league_table.models import Tournament, Match, Group, Participant
from league_table.forms import TournamentCreateForm

class TournamentListView(ListView):
    model = Tournament
    context_object_name = u"tournaments"
    template_name = u"league_table/tournament_list.html"

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(TournamentListView, self).dispatch(*args, **kwargs)


class TournamentDeleteView(DeleteView):
    model = Tournament
    success_url = reverse_lazy(u"tournament_list_url")

    def get(self, request, *args, **kwargs):
        raise Http404()

class TournamentCreateView(CreateView):
    model = Tournament
    form_class = TournamentCreateForm
    success_url = reverse_lazy(u"tournament_list_url")
    template_name = u"league_table/tournament_create.html"


class TournamentInfoView(TemplateView):
    model = Tournament
    success_url = reverse_lazy(u"tournament_info_url")
    template_name = u"league_table/tournament_info.html"

    def _get_tournament_table(self, tournament, group_name):
        group = Group.objects.filter(
            tournament = tournament,
            name = group_name,
        )
        matches = (Match.objects.filter(group = group)
                                .filter(participant1__isnull = False)
                                .filter(participant2__isnull = False))
        participants_pk = (
            set(matches.values_list("participant1", flat = True)) |
            set(matches.values_list("participant2", flat = True))
        )
        participants = Participant.objects.filter(
            pk__in = participants_pk
        )

        tournament_table = []
        for participant in participants:
            games_with_participant = matches.filter(
                Q(participant1_score__isnull = False) &
                (Q(participant1 = participant) |
                 Q(participant2 = participant))
            )
            number_of_games = games_with_participant.count()
            winnings = games_with_participant.filter(
                winner = participant
            ).count()
            losses = (games_with_participant.exclude(winner = participant)
                .exclude(winner__isnull = True)
            ).count()
            draws = number_of_games - (losses + winnings)
            points = (winnings * Tournament.POINTS_FOR_WIN +
                      draws * Tournament.POINTS_FOR_DRAW)
            participant1_goal_delta = games_with_participant.filter(
                participant1 = participant
            ).aggregate(
                goal_delta = (Sum("participant1_score") -
                                Sum("participant2_score"))
            )["goal_delta"] or 0
            participant2_goal_delta = games_with_participant.filter(
                participant2 = participant
            ).aggregate(
                goal_delta = (Sum("participant2_score") -
                                Sum("participant1_score"))
            )["goal_delta"] or 0

            table_item = {
                "participant": participant.name,
                "number_of_games": number_of_games,
                "winnings": winnings,
                "losses": losses,
                "points": points,
                "goal_delta": (participant1_goal_delta +
                                participant2_goal_delta),
            }
            tournament_table += [table_item]

        sorted_tournament_table = sorted(
            tournament_table,
            key = itemgetter("points", "goal_delta"),
            reverse = True
        )
        return sorted_tournament_table

    def _get_playoff_level_name(self, number):
        if (number == 0):
            return u"Финал"
        elif (number == 1):
            return u"Полуфинал"
        elif (number == 2):
            return u"Четвертьфинал"
        else:
            return u"1/{}".format(2 ** number)

    def _get_playoff_main_season(self, tournament_groups):
        main_season_group = tournament_groups.get(
            type = Group.PLAYOFF_MAIN_SEASON
        )
        main_group_matches = Match.objects.filter(
            group = main_season_group
        )
        playoff_levels = int(math.log(main_group_matches.count() + 1, 2))
        playoff_main_season = []
        for level in range(playoff_levels):
            current_level_matches = {
                "name": self._get_playoff_level_name(level),
                "rank": 2 ** level,
                "matches": main_group_matches.filter(
                    level = level
                ).order_by("number")
            }
            playoff_main_season += [current_level_matches]

        playoff_main_season = sorted(
            playoff_main_season,
            key = itemgetter("rank"),
            reverse = True
        )
        return playoff_main_season


    def get_tournament_groups(self, tournament):
        groups = {}
        tournament_groups = Group.objects.filter(tournament = tournament)

        if (tournament.type == Tournament.ROUND_ROBIN_TOURNAMENT or
            tournament.type == Tournament.ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT):
            groups["round_robin_group_season"] = tournament_groups.filter(
                type = Group.ROUND_ROBIN_GROUP_SEASON
            )
            groups["round_robin_main_season"] = tournament_groups.filter(
                type = Group.ROUND_ROBIN_MAIN_SEASON
            )

        if (tournament.type == Tournament.PLAYOFF_TOURNAMENT or
            tournament.type == Tournament.ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT):
            groups["playoff_regular_season"] = tournament_groups.filter(
                type = Group.PLAYOFF_REGULAR_SEASON
            )
            groups["playoff_main_season"] = self._get_playoff_main_season(
                tournament_groups
            )
        return groups

    def get_context_data(self, **kwargs):
        context = super(TournamentInfoView, self).get_context_data()
        pk = kwargs["pk"]
        tournament = Tournament.objects.get(pk = pk)
        groups = Group.objects.filter(tournament = tournament)

        if (tournament.type == Tournament.ROUND_ROBIN_TOURNAMENT):
            table = self._get_tournament_table(tournament, "main season")
            context["tournament_table"] = table

        matches = Match.objects.filter(
            Q(group__in = groups) &
            Q(participant1__isnull = False) & Q(participant2__isnull = False)
        ).order_by('number')

        context["groups"] = self.get_tournament_groups(tournament)
        context["tournament"] = tournament
        context["matches"] = matches
        context["const"] = Tournament
        return context

league_table/templates/league_table/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% block includes %}
    <link rel="stylesheet" href="{% static 'css/simple_style.css'%}">
    {% endblock includes %}
</head>
    <body>
    {% block content %}
    {% endblock content %}
    </body>
</html>

league_table/templates/league_table/circular_matches_schedule_staff.html
<table class="round-robin-schedule simple-table">
    <caption>{{ group_name }} </caption>
    <tr>
        <th>Дата</th>
        <th>Участники</th>
        <th>Счет</th>
        <th>Победитель</th>
    </tr>
    {% for match in matches %}
    <tr>
        <td><input name="match-date-{{match.pk}}" type="date"></td>

        <td class="clearfix">
            <div class="match-participant1">{{ match.participant1 }}</div>
            <div class="match-participant-delimiter">-</div>
            <div class="match-participant2">{{ match.participant2 }}</div>
        </td>

        {% if not match.participant1_score or not match.participant2_score %}
            <td>
                <input class="match-score" type="number" min=0 name="match-score1-{{match.pk}}">
                <span>-</span>
                <input class="match-score" type="number" min=0 name="match-score2-{{match.pk}}">
            </td>
        {% else %}
            <td>{{ match.participant1_score }} - {{ match.participant2_score }}</td>
        {% endif %}

        <td>
            <select class="match-winner" name="match-winner-{{match.pk}}">
                <option value="-1">--------</option>
                <option value="{{ match.participant1.pk }}">{{ match.participant1 }}</option>
                <option value="{{ match.participant2.pk }}">{{ match.participant2 }}</option>
            </select>
        </td>

    </tr>
    {% endfor %}

</table>

league_table/templates/league_table/playoff_schedule_staff.html
<div class="playoff-schedule">
    <table class="simple-table">
    </table>
</div>

league_table/templates/league_table/playoff_tournament.html
<div class="tournament-schedule">
    {% for group in groups.playoff_regular_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.match_set.all %}
    {% endfor %}
    {% for group in groups.playoff_main_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.matches %}
    {% endfor %}
</div>

league_table/templates/league_table/round_robin_and_playoff_tournament.html
<div class="tournament-schedule">
    {% for group in groups.round_robin_group_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.match_set.all %}
    {% endfor %}
    {% for group in groups.round_robin_main_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.match_set.all %}
    {% endfor %}
    {% for group in groups.playoff_regular_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.match_set.all %}
    {% endfor %}
    {% for group in groups.playoff_main_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.matches %}
    {% endfor %}
</div>

league_table/templates/league_table/round_robin_tournament.html
<div class="tournament-schedule">
    {% for group in groups.round_robin_group_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=groupname matches=group.match_set.all %}
    {% endfor %}
    {% for group in groups.round_robin_main_season %}
        {% include "league_table/circular_matches_schedule_staff.html" with group_name=group.name matches=group.match_set.all %}
    {% endfor %}
</div>

league_table/templates/league_table/tournament_create.html
{% extends "league_table/base.html" %}
{% load staticfiles %}

{% block includes %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/login_panel.css' %}">
    <link rel="stylesheet" href="{% static 'league_table/css/tournament_create.css' %}">
{% endblock includes %}

{% block content %}
<div class="main-centered-block">
    <div class="container">
        {% include "login_panel.html" %}
        <div class="tournament-form">
            <h1>Создание турнира</h1>
            <form method="post">{% csrf_token %}
                <table class = "tournament-form-fields">
                    <tr class="field-wrapper">
                        <td><label for="{{ form.name.id_for_label }}">Название чемпионата:</label></td>
                        <td>{{ form.name }}</td>
                        <td class="field-wrapper-errors">{{ form.name.errors }}</td>
                    </tr>
                    <tr class="field-wrapper">
                        <td><label for="{{ form.type.id_for_label }}">Тип:</label></td>
                        <td>{{ form.type }}</td>
                        <td class="field-wrapper-errors">{{ form.type.errors }}</td>
                    </tr>
                    <tr class="field-wrapper">
                        <td><label for="{{ form.number_of_groups.id_for_label }}">Количество групп:</label></td>
                        <td>{{ form.number_of_groups }}</td>
                        <td class="field-wrapper-errors">{{ form.number.errors }}</td>
                    </tr>
                    <tr div class="field-wrapper">
                        <td><label for="{{ form.participants.id_for_label }}">Участники:</label></td>
                        <td>{{ form.participants }}</td>
                        <td class="field-wrapper-errors">{{ form.participants.errors }}</td>
                    </tr>
                </table>
                <div class="tournament-form-buttons">
                    <input type="submit" value="Создать" class="tournament-form-submit simple-button simple-button__border">
                    <a href="{% url 'tournament_list_url' %}" class="tournament-form-cancel simple-button simple-button__border">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

league_table/templates/league_table/tournament_info.html
{% extends "league_table/base.html" %}
{% load staticfiles %}

{% block includes %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'league_table/css/tournament_info.css' %}">
    <link rel="stylesheet" href="{% static 'league_table/css/circular_matches_schedule.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_panel.css' %}">
{% endblock includes %}

{% block content %}
<div class="main-centered-block">
    <div class="container">
        {% include "login_panel.html" %}

        {% if tournament.type == const.ROUND_ROBIN_TOURNAMENT or tournament.type == const.ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT %}
            {% include "league_table/tournament_table.html" with tournament_table=tournament_table tournament=tournament %}
        {% endif %}

        <form class="matches-schedule" method="post">{% csrf_token %}
            {% if tournament.type == const.ROUND_ROBIN_TOURNAMENT %}
                {% include "league_table/round_robin_tournament.html" with groups=groups %}
            {% elif tournament.type == const.PLAYOFF_TOURNAMENT %}
                {% include "league_table/playoff_tournament.html" with groups=groups %}
            {% elif tournament.type == const.ROUND_ROBIN_AND_PLAYOFF_TOURNAMENT %}
                {% include "league_table/round_robin_and_playoff_tournament.html" with groups=groups %}
            {% endif %}
        </form>

    </div>
</div>
{% endblock content %}

league_table/templates/league_table/tournament_list.html
{% extends "league_table/base.html" %}
{% load staticfiles %}

{% block includes %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'league_table/css/tournament_list.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_panel.css' %}">
{% endblock includes %}

{% block content %}
<div class="main-centered-block">
    <div class="container">
        {% include "login_panel.html" %}
        <div class="title clearfix">
            <h1 class="title-text">Турниры</h1>
            <form class="title-action" method="post">{% csrf_token %}
                <button formaction="{% url 'tournament_create_url' %}" class="simple-button simple-button__border">Создать турнир</button>
            </form>
        </div>
        <table class="tournaments">
        {% for tournament in tournaments %}
            <form method="post">{% csrf_token %}
                <tr class="tournament">
                    <td class="tournament-name"><a class="simple-link" href="{% url 'tournament_info_url' pk=tournament.pk %}">{{ tournament.name }}</a></td>
                    <td class="tournament-delete">
                        <button class="tournament-delete-button simple-button" formaction="{% url 'tournament_delete_url' pk=tournament.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    </td>
                </tr>
            </form>
        {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

league_table/templates/league_table/tournament_table.html
<div class="tournament_table">
    <table class="simple-table">
        <caption>Турнирная таблица. {{ tournament.name }}.</caption>
        <tr>
            <th>Место</th>
            <th>Участник</th>
            <th>Очки</th>
            <th>Количество игр</th>
            <th>Победы</th>
            <th>Поражения</th>
            <th>Разница выигранных/ проигранных партий</th>
        </tr>
        {% for item in tournament_table %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.participant }}</td>
                <td>{{ item.points }}</td>
                <td>{{ item.number_of_games }}</td>
                <td>{{ item.winnings }}</td>
                <td>{{ item.losses }}</td>
                <td>{{ item.goal_delta }}</td>
            </tr>
        {% endfor %}
    </table>
</div>